### ISSUE TITLE
Difficult to pick the right portal to remove from my watch list

### ISSUE THREAD

**Issue by ichthyos** [metzen/ingress-notify#7]
On wide screens it's difficult to pick the right x to hit on the right side.

Maybe we can add a hover effect or alternating background colors in the rows.

**Comment by metzen** [comment]
I have some plans for the UI of the portal list page to add a map and some other enhancements which will make the layout a bit better for larger screens. A hover background color sounds fine for now. Fixed in e4eb9523693675720308cadf1eac2bb6969a6d99
